import AccordionCard from "./AccordionCard";
const Faq = () => {
  const faqs = [
    { question: "What is a Password Generator?", answer: "A Password Generator is an online tool that helps you create strong, random passwords for your accounts, ensuring they are secure and hard to guess." },
    { question: "Why should I use a Password Generator?", answer: "Using a Password Generator helps create passwords that are much more secure than manually created passwords, protecting your online accounts from unauthorized access." },
    { question: "How does this Password Generator work?", answer: "Our Password Generator creates random passwords based on your preferences, such as desired length and inclusion of uppercase letters, numbers, and symbols." },
    { question: "Are the passwords generated really secure?", answer: "Yes, the passwords generated are highly secure as they are created randomly and contain a mix of different character types." },
    { question: "Can I customize the length and characters of the password?", answer: "Yes, you can customize the password length and choose to include or exclude uppercase letters, lowercase letters, numbers, and symbols." },
    { question: "Is the password saved anywhere?", answer: "No, the passwords generated by this tool are not saved anywhere, ensuring your privacy and security." },
    { question: "How long should my password be?", answer: "A strong password should typically be at least 12-16 characters long to resist attacks." },
    { question: "What makes a password strong?", answer: "A strong password contains a mix of uppercase and lowercase letters, numbers, and symbols, and should be long enough to resist brute-force attacks." },
    { question: "Can I use this Password Generator for all my accounts?", answer: "Yes, you can use this tool to create secure passwords for all your online accounts." },
    { question: "How often should I change my password?", answer: "It is recommended to change your passwords every 3 to 6 months or immediately if you suspect any suspicious activity." },
    { question: "How do I store generated passwords securely?", answer: "You can use a password manager to securely store your generated passwords." },
    { question: "Is this tool free to use?", answer: "Yes, our Password Generator tool is completely free to use." },
    { question: "Is it safe to generate passwords on this tool?", answer: "Yes, it is safe to generate passwords on this tool as the generation happens locally in your browser." },
    { question: "What should I do if I lose my password?", answer: "If you lose a password, you can reset it using the recovery options provided by the service." },
    { question: "What is two-factor authentication (2FA) and should I use it?", answer: "Two-factor authentication (2FA) adds an extra layer of security by requiring a second form of verification; it is highly recommended for important accounts." },
  ];

  return (
    <section className="main-content">
      <h1 className="text-center text-uppercase fs-1 my-5">Frequently Asked Questions</h1>
      <div className="row flex-center p-2">
        <div className="col-sm-8 offset-sm-2">
          <div id="accordion">
            {faqs.map((faq, index) => {
              return <AccordionCard key={index} question={faq.question} answer={faq.answer} />;
            })}
          </div>
        </div>
      </div>
    </section>
  );
};

export default Faq;
